name: Lint Commit Messages
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Copy commitlint config
        run: cp .commitlintrc.json $HOME/.commitlintrc.json

      - name: Validate PR commits
        run: nix-shell -p commitlint --run "commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose"
        